In [95]:
import pandas as pd
foods = pd.read_json('themacrodiet-s-export.json')

In [96]:
foods

,-M3ZD20Kqf74j5J1oFUd,-M3ZDExHO7Eyo8hahwgv,-M3ZDQVX9NTW4hqzCtU5,-M3ZDZ6ASOOpPcGC6qBf,-M3ZDifC1k4ByVH7ZhQW,-M3ZDpXl5Uox77_5naZu,-M3ZDwbSq4sij7pYTtHE,-M3ZE3F74fSau_g7nkwb,-M3ZEDwJFal6TZ42fcUJ,-M3ZEMbwp863DXtRkhHZ,...,-MWF5HfHXJFn3xgJmaFc,-MWJeYFBh6yhoFhTkQm9,-MWKdFHzTGTiiKWHrb1j,-MXbjDW_rHcZt1lZNP2O,-MY5gVYyHvJZlE4_iz2T,-MYf6frTF8s_J8jyk8BY,-MYpT6xtPJWiM7adxrno,-MYpTLTGGu6EqX6w9DKA,-MZ4YnDcGuLa4QIJpYf5,-MZ4a3LDuXBeQi_lO8MQ
Calories,576,596,625,106,16,16,360,355,64,74,...,244,375,385,99,112,277,185,18,119,97
Carbohydrates,22,11.6,7.4,0,0.2,3.6,7.5,0.36,12,15.6,...,0,5.2,5,0,0,5.1,5.5,.9,4.7,0
Fats,49,46.0,52,1.1,1.6,0.1,1.1,0.99,0.1,0.3,...,14,1.6,5.5,2.5,1.07,28,17,.2,9.4,14
Name,Almonds,Peanut Butter Meridian Smooth,Almond Butter Pip & Nut,Chicken Breast Tesco,Koko Dairy Free Unsweetened Calcium,Cucumber,ISO100 Gourmet Chocolate,ISO-XP Applied Nutrition Chocolate Dessert,Ketchup Heinz Tomato 50% Less Sugar & Salt,Blueberries Frozen Tesco,...,Sirloin Steak Raw,BioTechUSA Iso Whey Zero Pistachio,BioTechUSA Pure Whey Cookies & Cream,Shrimps Jinga Ocean Sea,Tuna Sevyco In Water Drained,Fresh Cream Vegetable Charalambides,Fresh Cream Light Charalambides 17% Fat,Mushrooms Sliced Premier,Tzatziki Tesco,Tequila
ServingAmount,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,1
ServingUnit,Grams,Grams,Grams,Grams,Grams,Grams,Grams,Grams,Grams,Grams,...,Grams,Grams,Grams,Grams,Grams,Milliliters,Milliliters,Grams,Grams,Shots
ServingUnitShortCode,g,g,g,g,g,g,g,g,g,g,...,g,g,g,g,g,ml,ml,g,g,shot
Protein,21,29.6,26,24,0.2,0.7,78,90,1.4,0.8,...,27,84,78,18.6,22.82,0.8,3.5,2.1,3.6,0
Saturated,3.7,8.2,4,0.3,1.4,0.1,0.6,0.04,0,0.1,...,6,1,3.9,0.6,0.79,28,12,0,4.5,14

In [97]:
foods = foods.T

In [98]:
foods

,Calories,Carbohydrates,Fats,Name,ServingAmount,ServingUnit,ServingUnitShortCode,Protein,Saturated
-M3ZD20Kqf74j5J1oFUd,576,22,49,Almonds,100,Grams,g,21,3.7
-M3ZDExHO7Eyo8hahwgv,596,11.6,46.0,Peanut Butter Meridian Smooth,100,Grams,g,29.6,8.2
-M3ZDQVX9NTW4hqzCtU5,625,7.4,52,Almond Butter Pip & Nut,100,Grams,g,26,4
-M3ZDZ6ASOOpPcGC6qBf,106,0,1.1,Chicken Breast Tesco,100,Grams,g,24,0.3
-M3ZDifC1k4ByVH7ZhQW,16,0.2,1.6,Koko Dairy Free Unsweetened Calcium,100,Grams,g,0.2,1.4
...,...,...,...,...,...,...,...,...,...
-MYf6frTF8s_J8jyk8BY,277,5.1,28,Fresh Cream Vegetable Charalambides,100,Milliliters,ml,0.8,28
-MYpT6xtPJWiM7adxrno,185,5.5,17,Fresh Cream Light Charalambides 17% Fat,100,Milliliters,ml,3.5,12
-MYpTLTGGu6EqX6w9DKA,18,.9,.2,Mushrooms Sliced Premier,100,Grams,g,2.1,0
-MZ4YnDcGuLa4QIJpYf5,119,4.7,9.4,Tzatziki Tesco,100,Grams,g,3.6,4.5
-MZ4a3LDuXBeQi_lO8MQ,97,0,14,Tequila,1,Shots,shot,0,14

In [99]:
foods.ServingUnit.unique()

array(['Grams', 'Burgers', 'Milliliters', 'Breasts', 'Candys',
       'Collins glasses', 'Servings', 'Slices', 'Chips', 'Doughnuts',
       'Dishes', 'Wings', 'Pieces', 'Bars', 'Sachets', 'Cookies',
       'Fruits', 'Packets', 'Pancakes', 'Shots'], dtype=object)

In [100]:
foods.ServingUnitShortCode.unique()

array(['g', 'burger', 'ml', 'breast', 'candy', 'collins glass', 'serving',
       'slice', 'chips', 'doughnut', 'dish', 'wing', 'piece', 'bar',
       'sachet', 'cookie', 'fruit', 'packet', 'pancake', 'shot'],
      dtype=object)

In [101]:
import firebase_admin
from firebase_admin import credentials

cred = credentials.Certificate('themacrodiet-s-firebase-adminsdk-f0h78-30db3d9e86.json')
default_app = firebase_admin.initialize_app(cred)

ValueError: The default Firebase app already exists. This means you called initialize_app() more than once without providing an app name as the second argument. In most cases you only need to call initialize_app() once. But if you do want to initialize multiple apps, pass a second argument to initialize_app() to give each app a unique name.

In [9]:
from firebase_admin import firestore
db = firestore.client()

In [33]:

doc_ref = db.collection(u'TheMacroDiet/Production/GlobalVariables').document(u'ServingUnits')

doc = doc_ref.get()
if doc.exists:
    print(f'Document data: {doc.to_dict()}')
    current_Serving_Units= doc
else:
    print(u'No such document!')

Document data: {'Milligrams': {'ShortCodePlural': 'mg', 'ShortCode': 'mg'}}

In [34]:
current_Serving_Units.to_dict()

{'Milligrams': {'ShortCodePlural': 'mg', 'ShortCode': 'mg'}}

In [43]:
servingUnitsDoc = {
   # u'stringExample': u'Hello, World!',
   # u'booleanExample': True,
   # u'numberExample': 3.14159265,
   # u'dateExample': datetime.datetime.now(),
   # u'arrayExample': [5, True, u'hello'],
   # u'nullExample': None,
    u'Grams': {
        u'ShortCode': u'g',
        u'ShortCodePlural': u'g'
    },
    u'Milligrams': {
        u'ShortCode': u'mg',
        u'ShortCodePlural': u'mg'
    },
    u'Pieces': {
        u'ShortCode': u'piece',
        u'ShortCodePlural': u'pieces'
    },
    u'Milliliters ': {
        u'ShortCode': u'ml',
        u'ShortCodePlural': u'ml'
    },
    u'Product': {
        u'ShortCode': u'product',
        u'ShortCodePlural': u'products'
    },
    u'Burgers': {
        u'ShortCode': u'burger',
        u'ShortCodePlural': u'burgers'
    },
    u'Breasts': {
        u'ShortCode': u'breast',
        u'ShortCodePlural': u'breasts'
    },
    u'Candys': {
        u'ShortCode': u'candy',
        u'ShortCodePlural': u'candys'
    },
    u'Collins glasses': {
        u'ShortCode': u'collins glass',
        u'ShortCodePlural': u'collins glasses'
    },
    u'Servings': {
        u'ShortCode': u'serving',
        u'ShortCodePlural': u'servings'
    },
    u'Slices': {
        u'ShortCode': u'slice',
        u'ShortCodePlural': u'slices'
    },
    u'Chips': {
        u'ShortCode': u'chip',
        u'ShortCodePlural': u'chips'
    },
    u'Doughnuts': {
        u'ShortCode': u'doughnut',
        u'ShortCodePlural': u'doughnuts'
    },
    u'Dishes': {
        u'ShortCode': u'dish',
        u'ShortCodePlural': u'dishes'
    },
    u'Wings': {
        u'ShortCode': u'wing',
        u'ShortCodePlural': u'wings'
    },
    u'Bars': {
        u'ShortCode': u'bar',
        u'ShortCodePlural': u'bars'
    },
    u'Sachets': {
        u'ShortCode': u'sachet',
        u'ShortCodePlural': u'sachets'
    },
    u'Cookies': {
        u'ShortCode': u'cookie',
        u'ShortCodePlural': u'cookies'
    },
    u'Fruits': {
        u'ShortCode': u'fruit',
        u'ShortCodePlural': u'fruits'
    },
    u'Packets': {
        u'ShortCode': u'packet',
        u'ShortCodePlural': u'packets'
    },
    u'Pancakes': {
        u'ShortCode': u'pancake',
        u'ShortCodePlural': u'pancakes'
    },
    u'Shots': {
        u'ShortCode': u'shot',
        u'ShortCodePlural': u'shots'
    }
}

In [44]:
servingUnitsDoc

{'Grams': {'ShortCode': 'g', 'ShortCodePlural': 'g'},
 'Milligrams': {'ShortCode': 'mg', 'ShortCodePlural': 'mg'},
 'Pieces': {'ShortCode': 'piece', 'ShortCodePlural': 'pieces'},
 'Milliliters ': {'ShortCode': 'ml', 'ShortCodePlural': 'ml'},
 'Product': {'ShortCode': 'product', 'ShortCodePlural': 'products'},
 'Burgers': {'ShortCode': 'burger', 'ShortCodePlural': 'burgers'},
 'Breasts': {'ShortCode': 'breast', 'ShortCodePlural': 'breasts'},
 'Candys': {'ShortCode': 'candy', 'ShortCodePlural': 'candys'},
 'Collins glasses': {'ShortCode': 'collins glass',
  'ShortCodePlural': 'collins glasses'},
 'Servings': {'ShortCode': 'serving', 'ShortCodePlural': 'servings'},
 'Slices': {'ShortCode': 'slice', 'ShortCodePlural': 'slices'},
 'Chips': {'ShortCode': 'chip', 'ShortCodePlural': 'chips'},
 'Doughnuts': {'ShortCode': 'doughnut', 'ShortCodePlural': 'doughnuts'},
 'Dishes': {'ShortCode': 'dish', 'ShortCodePlural': 'dishes'},
 'Wings': {'ShortCode': 'wing', 'ShortCodePlural': 'wings'},
 'Bars': {'ShortCode': 'bar', 'ShortCodePlural': 'bars'},
 'Sachets': {'ShortCode': 'sachet', 'ShortCodePlural': 'sachets'},
 'Cookies': {'ShortCode': 'cookie', 'ShortCodePlural': 'cookies'},
 'Fruits': {'ShortCode': 'fruit', 'ShortCodePlural': 'fruits'},
 'Packets': {'ShortCode': 'packet', 'ShortCodePlural': 'packets'},
 'Pancakes': {'ShortCode': 'pancake', 'ShortCodePlural': 'pancakes'},
 'Shots': {'ShortCode': 'shot', 'ShortCodePlural': 'shots'}}

In [46]:
db.collection(u'TheMacroDiet/Production/GlobalVariables').document(u'ServingUnits').set(servingUnitsDoc);

In [129]:
for ind in foods.index:
    name = foods['Name'][ind]
    foodData = {
        u'Name': name.encode('utf-8','ignore').decode('utf-8'),
        u'Calories': int(foods['Calories'][ind]),
        u'Carbohydrates': float(foods['Carbohydrates'][ind]),
        u'Fats': float(foods['Fats'][ind]),
        u'Protein': float(foods['Protein'][ind]),
        u'Saturated': float(foods['Saturated'][ind]),
        u'ServingAmount': float(foods['ServingAmount'][ind]),
        u'ServingUnit': foods['ServingUnit'][ind],
        u'ServingUnitShortCode': foods['ServingUnitShortCode'][ind],
       # u'booleanExample': True,
       # u'numberExample': 3.14159265,
       # u'dateExample': datetime.datetime.now(),
       # u'arrayExample': [5, True, u'hello'],
       # u'nullExample': None,
    }
    doc_ref = db.collection(u'TheMacroDiet/Production/GlobalFoodDatabase').add(foodData)

In [127]:
foodData

{'Name': 'Almond Butter Pip & Nut',
 'Calories': 625,
 'Carbohydrates': 7.4,
 'Fats': 52.0,
 'Protein': 26.0,
 'Saturated': 4.0,
 'ServingAmount': 100.0,
 'ServingUnit': 'Grams',
 'ServingUnitShortCode': 'g'}

In [53]:
aaaaaa

[<google.cloud.firestore_v1.base_document.DocumentSnapshot at 0x7f44c0f1fdf0>,
 <google.cloud.firestore_v1.base_document.DocumentSnapshot at 0x7f44c0f1fd30>]